### ISSUE TITLE
Pool generation algorithm question

### ISSUE THREAD

**Issue by metaraine** [copperdogma/mtgen#2] opened 2016-02-29 02:20 UTC
How are packs generated? Is it just random within the given number of rarity levels, or it more complicated? Thanks :).

**Comment by copperdogma** [comment] 2016-02-29 02:37
Depends on the booster, but let's take an example from the 2015 Core Set standard 16-card booster.

You can see the packdef file here (I just made the format up myself): http://mtgen.net/m15/packs.json

In that you can find this pack def:
 		,{
		"packName": "m15-standard",
		"packDesc": "2015 Core Set: Standard Booster",
		"isGenerated": true,
		"cards": [
			{ "query": "from[m15]?type='Basic Land'" }
			,{ "query": "take[9]>from[m15_main]?rarity='c'" }
			,{ "querySet": [ { "percent": 75, "query": "from[m15_main]?rarity='c'" }
							,{ "percent": 25, "query": "from[m15_foils]", "canBeDuplicate": true, "setValues": { "foil": true }, "_comment": "25% chance rare is a foil of any card, including land" }
							] }
			,{ "query": "take[3]>from[m15_main]?rarity='u'" }
			,{ "querySet": [ { "percent": 87.5, "query": "from[m15_main]?rarity='r'" }
							,{ "percent": 12.5, "query": "from[m15_main]?rarity='m'", "_comment": "rare=7/8, mythicRare=1/8" } 
							] }
			,{ "querySet": [ { "percent": 50, "query": "from[m15]?type='Marketing'" }
							,{ "percent": 50, "query": "from[m15]?token=true-from[m15]?promo=true" } 
							] }
			]
		}

So each query corresponds to one or more slots. In English it looks like this:

slot 1: random basic land
slot 2-10: random common card
slot 11: 75% chance of a random common, 25% chance of a random foil card (that could be any rarity)
slot 12-14: random uncommon card
slot 15: 87.5% chance of a random rare, 12.5% chance of a random mythic
slot 16: 50/50 chance of a Tip ("marketing") or Token card (I'm sure no one cares about this;)

There's a bit of logic in there to ensure the same card isn't chosen twice (except for foils which may be a dupe of a card already in the set).

Is that what you were asking?

**Comment by metaraine** [comment] 2016-02-29 15:26
Yes, nice to know, and thanks for the explanation! I'm looking forward to
using this with Shadows over Innistrad in preparation for GP Albuquerque.

**Closed** 2016-02-29 15:34 UTC
